name: well_being
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.8
  usage_stats: ^1.1.1 
  permission_handler: ^11.0.1
  http: ^1.1.0
  google_generative_ai: ^0.4.6
  intl: ^0.20.2
  table_calendar: ^3.0.8
  flutter_svg: ^2.0.7
  flutter_markdown: ^0.6.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_lints: ^5.0.0
  

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/house/empty_lot.svg
    - assets/house/foundation.svg
    - assets/house/walls.svg
    - assets/house/roof.svg
    - assets/house/windows.svg
    - assets/house/doors.svg
    - assets/store/pen.jpg
    - assets/store/bottle.jpg
    - assets/store/diary.jpg
    - assets/store/tshirt.jpg
    - assets/store/stickers.jpg
    - assets/store/mug.jpg
